import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import PrimeVue from 'primevue/config';
import 'primevue/resources/themes/saga-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';
import PrimeVueButton from 'primevue/button'; 
import InputText from 'primevue/inputtext';
import InputNumber from 'primevue/inputnumber';
import PasswordText from 'primevue/password';
import PrimeCalendar from 'primevue/calendar';
import ToastService from 'primevue/toastservice';
import PrimeToast from 'primevue/toast';
import PrimeColumn from 'primevue/column';
import PrimeDataTable from 'primevue/datatable';
import PrimeCheckBox from 'primevue/checkbox';
import ToggleButton from 'primevue/togglebutton';
import RadioButton from 'primevue/radiobutton';
import PrimeDropdown from 'primevue/dropdown';
import PrimeDialog from 'primevue/dialog';

const app = createApp(App);
app.use(PrimeVue);
app.component('PrimeButton', PrimeVueButton);
app.component('InputText', InputText);
app.component('InputNumber', InputNumber);
app.component('PasswordText', PasswordText);
app.component('PrimeCalendar', PrimeCalendar);
app.component('PrimeDialog', PrimeDialog);
app.use(ToastService);
app.component('PrimeToast', PrimeToast);
app.component('PrimeColumn', PrimeColumn);
app.component('PrimeDataTable', PrimeDataTable);
app.component('ToggleButton',ToggleButton);
app.component('PrimeCheckBox',PrimeCheckBox);
app.component('RadioButton',RadioButton);
app.component('PrimeDropdown',PrimeDropdown);
app.use(router);
app.mount('#app');
