name: Spring Boot CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: |
          mvn clean verify

        env:
          SOME_CONFIG: ${{ secrets.SOME_CONFIG }}
          ANOTHER_CONFIG: ${{ secrets.ANOTHER_CONFIG }}


