name: Spring Boot CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
